# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$fibnum = 1
$fibnumprevious = 1
$sumevens = 0

while $fibsum <= 40 do
  $fibnumnew = $fibnum + $fibnumprevious
  $fibnumprevious = $fibnum
  $fibnum = $fibnumnew
  if $fibsum % 2 == 0
    $sumevens = $sumevens + $fibnum
    puts "Sum of Even Fibonacci Numbers" {$sumevens}
  end
end